# Generated by Django 4.2.1 on 2023-07-14 08:37

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, validators=[App.models.valid_name]),
        ),
    ]
