# Generated by Django 4.2.1 on 2023-07-14 09:09

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_topic_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessrecord',
            name='author',
            field=models.CharField(max_length=100, validators=[App.models.valid_name, App.models.valid_size]),
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=100, validators=[App.models.valid_size]),
        ),
    ]
